# -*- coding: utf-8 -*-
{
    'name': 'Studio customizations',
    'version': '11.0.1.0',
    'category': 'Studio',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'DigitalHub Distribution Sprl',
    'depends': [
        'account',
        'account_intrastat',
        'base',
        'calendar',
        'delivery',
        'delivery_barcode',
        'edi_base',
        'edi_agora',
        'edi_backmarket',
        'mass_mailing',
        'product',
        'purchase',
        'sale',
        'sales_team',
        'sale_management',
        'stock',
        'stock_account',
        'tax_margin',
        'web_studio',
        'website_sale',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_model_access.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
